### ISSUE TITLE
malloclab 명시적 가용 리스트 - 힙 초기화

### ISSUE THREAD

**Issue by spamstar** [yumXD/malloclab#24]
## 어떤 기능인가요?

> 명시적 가용 리스트 - 힙 초기화 및 이중 포인터 설정

## 작업 상세 내용

- [x] mm_init: 힙 초기화

**Comment by Yoosun-Chang** [comment]
오 이해하셨나요?

**Comment by spamstar** [comment]
> 오 이해하셨나요?

뭐 그럭저럭
